default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 500

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db_name) %>
  username: <%= Rails.application.credentials.dig(:db_username) %>
  password: <%= Rails.application.credentials.dig(:db_password) %>
  host: <%= Rails.application.credentials.dig(:db_host) %>

test:
  <<: *default
  database: <%= ENV['MYSQL2_DATABASE_TEST'] %>
  username: <%= ENV['MYSQL2_USERNAME_TEST'] %>
  password: <%= ENV['MYSQL2_PASSWORD_TEST'] %>
  host: <%= ENV['MYSQL2_HOST_TEST'] %>

staging:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db_name) %>
  username: <%= Rails.application.credentials.dig(:db_username) %>
  password: <%= Rails.application.credentials.dig(:db_password) %>
  host: <%= Rails.application.credentials.dig(:db_host) %>